### ISSUE TITLE
Can I use this remark plugin in milkdown editor?

### ISSUE THREAD

**Issue by Innei** [hyoban/remark-github-alerts#1]
I want to implement this syntax in milkdown and found this plugin. Thank you very much.

I injected the remark plugin into the milkdown plugin through the built-in method $remark(), but it didn't take effect. I didn't make any modifications to mdast. Did I use it incorrectly?

This is the minimal reproduction: https://github.com/Innei/milkdown-remark-plugin

**Comment by hyoban** [comment]
I'm not very familiar with milkdown, this may be related to https://github.com/Milkdown/milkdown/issues/501.

And for this plugin to work, the order of plugin is important. If you move this plugin to top, you will get something like this. I think this plugin can not be used without `remarkRehype`.

```html
<blockquote>
  <p>
    <span
      data-value='<svg class="octicon octicon-info mr-2" viewBox="0 0 16 16" version="1.1" width="16" height="16" aria-hidden="true"><path d="M0 8a8 8 0 1 1 16 0A8 8 0 0 1 0 8Zm8-6.5a6.5 6.5 0 1 0 0 13 6.5 6.5 0 0 0 0-13ZM6.5 7.75A.75.75 0 0 1 7.25 7h1a.75.75 0 0 1 .75.75v2.75h.25a.75.75 0 0 1 0 1.5h-2a.75.75 0 0 1 0-1.5h.25v-2h-.25a.75.75 0 0 1-.75-.75ZM8 6a1 1 0 1 1 0-2 1 1 0 0 1 0 2Z"></path></svg>'
      data-type="html"
      contenteditable="false"
      class="ProseMirror-selectednode"
      draggable="true"
      >&lt;svg class="octicon octicon-info mr-2" viewBox="0 0 16 16"
      version="1.1" width="16" height="16" aria-hidden="true"&gt;&lt;path d="M0
      8a8 8 0 1 1 16 0A8 8 0 0 1 0 8Zm8-6.5a6.5 6.5 0 1 0 0 13 6.5 6.5 0 0 0
      0-13ZM6.5 7.75A.75.75 0 0 1 7.25 7h1a.75.75 0 0 1 .75.75v2.75h.25a.75.75 0
      0 1 0 1.5h-2a.75.75 0 0 1 0-1.5h.25v-2h-.25a.75.75 0 0 1-.75-.75ZM8 6a1 1
      0 1 1 0-2 1 1 0 0 1 0 2Z"&gt;&lt;/path&gt;&lt;/svg&gt;</span
    >Note
  </p>
  <p>
    Highlights information that users should take into account, even when
    skimming.
  </p>
</blockquote>
```

**Comment by Innei** [comment]
I tried, to move this remark plugin to the top, it can process the blockquote, but the markdown serializer is wrong.
![CleanShot 2024-02-03 at 1  36 41@2x](https://github.com/hyoban/remark-github-alerts/assets/41265413/8d5f3c0d-d1fd-4df3-9547-1b9f52f8ef08)

Because the `type: blockquote` nest the `type: html` it will not parse it into prosemirror view.

In my opinion, there is a way to define a new type for this markdown token instead of re-use the blockquote type. If do that, I think it can define a new prosemirror node view for this new type.

Anyway, thank you for your answer
